# A YAML template example.
kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: nginx:alpine
    commands:
        - cp . /usr/share/nginx/html
  - name: publish  
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: vqhuy/about-me